### ISSUE TITLE
Trying to load a style that does not exist kills the interface

### ISSUE THREAD

**Issue by ARolek** [go-spatial/fresco#10]
I tried opening a style I was working on in icognito mode and the UI breaks. For example: https://justenpalmer.github.io/fresco/#/style/ciwf4zbsv007y2pmt2rspc1dc/layer/transit-lines
<img width="617" alt="screen shot 2018-04-16 at 9 56 31 am" src="https://user-images.githubusercontent.com/667850/38823884-769d79e0-415c-11e8-8305-cefb628a77db.png">

**Comment by justenPalmer** [comment]
Non-existent styles no longer crash the interface on dev. It should be handled better than it is right now though (blank screen)
