### ISSUE TITLE
Support for mapbox:// sources

### ISSUE THREAD

**Issue by ARolek** [go-spatial/fresco#23]
If you use a mapbox source you need to supply an API token. You can use the attached style to see the error. 
[scoutred-satellite.json.zip](https://github.com/justenPalmer/fresco/files/1917538/scoutred-satellite.json.zip)

**Comment by justenPalmer** [comment]
Open issue with mapbox-gl to have them trigger the on('error') event when there is a missing ACCESS_TOKEN. This will enable missing access token errors to be signaled to the user.
