### ISSUE TITLE
Add a copy/paste layer functionality

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/fresco#25]
Add a way to duplicate a layer along with its styling.

**Comment by PetersonGIS** [comment]
Any way to prioritize this one? Copying and pasting layers in order to tweak one thing or another is pretty much what I do all day. :)

It will be so much easier when this can be done in the interface instead of the code. When you do this with the code you have to make sure you scroll around and put the new layer in the right place, which ends badly sometimes (if you accidentally put it within another bracket or in the wrong place or whatever). I think that you could just add a "_copy" to the end of the newly copied layer to change its id.

**Comment by justenPalmer** [comment]
@PetersonGIS, this has been added! Try it by using the dropdown menu in any layer.
<img width="297" alt="screen shot 2018-06-05 at 12 50 59 am" src="https://user-images.githubusercontent.com/1915862/40962532-a3a08872-685a-11e8-8d73-a386ea195dbc.png">

**Comment by PetersonGIS** [comment]
Nice! It works well for me. Thanks!
