### ISSUE TITLE
Long style names push controls to next line [screenshot]

### ISSUE THREAD

**Issue by ARolek** [go-spatial/fresco#32]
<img width="501" alt="screen shot 2018-04-22 at 10 21 04 pm" src="https://user-images.githubusercontent.com/667850/39108155-9f62aa52-467b-11e8-8509-c7a6b977ac7b.png">

**Comment by justenPalmer** [comment]
Fixed.
<img width="355" alt="screen shot 2018-06-07 at 6 33 12 pm" src="https://user-images.githubusercontent.com/1915862/41134463-4a6cef56-6a81-11e8-89b8-e86d88024f2c.png">
