### ISSUE TITLE
Add layer edit property interface

### ISSUE THREAD

**Issue by justenPalmer** [go-spatial/fresco#4]

**Comment by justenPalmer** [comment]
Added but needs enhancement. 
- Arrays are not supported.
- Needs better keyboard flow controls.

**Comment by knownasilya** [comment]
boolean type isn't found also you cannot delete an attribute once you've selected it.

**Comment by justenPalmer** [comment]
@knownasilya, this has now been addressed. Boolean type is in.

**Comment by justenPalmer** [comment]
Interface is in, but UX needs polishing.
