### ISSUE TITLE
When adding a source that throws an error the user is not notified

### ISSUE THREAD

**Issue by ARolek** [go-spatial/fresco#41]
When adding a source that's invalid, the source is added to the source list and error is thrown in the console but the user is not notified and they're not taken to a map. Error console:

<img width="775" alt="screen shot 2018-04-30 at 12 16 22 pm" src="https://user-images.githubusercontent.com/667850/39446258-bfe90986-4c72-11e8-8b45-6fe17c8f1de9.png">

**Comment by justenPalmer** [comment]
Source error reporting has been dramatically improved in the dev version. Let's close this issue to focus on the new bugs that might arise.
