### ISSUE TITLE
Ability to set feature state on features

### ISSUE THREAD

**Issue by justenPalmer** [go-spatial/fresco#55]
When developing an interactive style the feature state will change based on user interactions. It would be helpful if a feature could have specific attributes set via `setFeatureState`  inside fresco to simulate the user interactions.

**Comment by justenPalmer** [comment]
This functionality is now available on dev: https://fresco-dev.gospatial.org/

**Comment by Jnb2387** [comment]
Great work on this project!

I love that expression are incorporated but how do you set the feature-state? I have a label that I am setting the color with feature-state on hover with:
[
  "case",
[
    "boolean",
    [
      "feature-state",
      "hover"
    ],
    false
  ],
  "yellow",
  "rgba(234, 228, 228, 1)"
]

I clicked on the layer so it becomes the focused layer and then set the key to hover and the value to true,  but this does not render any changes.

**Comment by ARolek** [comment]
@Jnb2387 did you hit the "play" button after you set the key and value? 
<img width="292" alt="Screen Shot 2020-05-25 at 8 59 15 PM" src="https://user-images.githubusercontent.com/667850/82859114-b0804480-9eca-11ea-9df3-9e14b0c456af.png">

**Comment by justenPalmer** [comment]
@Jnb2387 Are you sure the `boolean` is correct? Maybe try an `==` operation instead.

**Comment by Jnb2387** [comment]
@ARolek I did hit the play button after every time I changed a value with no luck.
@justenPalmer I may not be understanding feature-state properly, I have only seen examples using the boolean type to trigger the feature-state. I think I am misunderstanding what goes in the key:value.

![image](https://user-images.githubusercontent.com/17630656/83158874-927d3480-a0c2-11ea-96bd-3ecf3c3814c5.png)

**Comment by justenPalmer** [comment]
@Jnb2387 I'm referring to your style expression. You're using the `boolean` expression which is used to change the type of data that follows it into a boolean. Instead, I believe your intent was to compare the hover value to the value false. Which would look like this instead:
```
[
  "==",
  [
    "feature-state",
    "hover"
  ],
  false
]
```
