### ISSUE TITLE
"TypeError: a.getIn is not a function" error after fresh install

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [go-spatial/fresco#62]
After doing 

1. clone
1. `npm install`
1. `npm start`

![image](https://user-images.githubusercontent.com/10080111/56839142-d90cb980-6846-11e9-8f8c-8695073b3026.png)

**Comment by justenPalmer** [comment]
I'll look into this. @RyanAtViceSoftware, thanks for logging this.

**Comment by RyanAtViceSoftware** [comment]
@justenPalmer thanks man! and no problem on logging the ticket

**Comment by ARolek** [comment]
@RyanAtViceSoftware can you try clearing your localStorage for the domain localhost:3000 to see if that fixes the problem? This is just a workaround but gives some insight into what might be going on.

**Comment by RyanAtViceSoftware** [comment]
@ARolek When I opened the browser it just worked!

![image](https://user-images.githubusercontent.com/10080111/56849087-cda4a700-68b5-11e9-9946-b5c5e319bf0c.png)

So @ARolek I'm a bit confused on what this does. We were looking for a parcel map. Does this take the JSON output of Scout Red and create a map?
