### ISSUE TITLE
https://fresco.gospatial.org can't load the map

### ISSUE THREAD

**Issue by linyq1874** [go-spatial/fresco#64]
When i open https://fresco.gospatial.org, I don't konw why it can't load the map.
It just like that.
![image](https://user-images.githubusercontent.com/31888566/60001057-2ca95100-9698-11e9-8d59-6b00a945a3d6.png)

**Comment by linyq1874** [comment]
I got it

**Comment by ARolek** [comment]
@linyq1874 what was the issue? It might be helpful for someone else or an improvement we can implement.
