### ISSUE TITLE
localStorage style parsing issues

### ISSUE THREAD

**Issue by ARolek** [go-spatial/fresco#65]
Fresco is unable to load my styles from local storage due to a parse error. When looking at localStorage, one of the keys is from mapbox and the value is not a JSON object. Fresco is iterating through all keys and expecting values to be in JSON format. A solution could be to prefix fresco keys with an identifier (i.e. `fresco-<map-id>` or `fresco.<map-id>`. This would  namespace the localStorage entries and avoid this issue.

**Comment by justenPalmer** [comment]
The new version of Fresco fixes this by putting all styles into a `frescoStyleStore` bucket
