### ISSUE TITLE
Give the new version of Fresco a try

### ISSUE THREAD

**Issue by ARolek** [go-spatial/fresco#74]
@justenPalmer has been working on a refactor of the Fresco codebase so it's easier to contribute to. This also came with a design refresh and we're looking for some help getting UX feedback and identifying bugs. Please give it a run: https://fresco-dev.gospatial.org

**Comment by ARolek** [comment]
@pnorman in case you're interested

**Comment by pnorman** [comment]
I'm having trouble getting started. Here are my notes

- When I make a new style it puts me into layers. It would make more sense to put me in sources, because I can't do useful layers without a source.

- Add layers tells me type is an enum. This isn't useful information at this stage because it's a dropdown. The screen space would be better taken explaining what type is.

- When I add a source I get a screen showing me the source layers.

- I told it to auto-create layers but it doesn't seem to have done that. When I go into the JSON I see layers, when I go to the layers panel I don't.

- When I added a layer from that screen it didn't appear right away. Going into the JSON source and editing it caused it to appear.

- The X on the red warning bar is almost invisible

**Comment by justenPalmer** [comment]
@pnorman this is solid feedback. 

- I'll change the default routing on a layer to send the user to sources if there isn't a source

- This data type information (enum) is available on all fields across Fresco. It becomes really useful in cases where the data type can switch from expression to number for example. I'll have to see if there might be some special cases where it should be hidden

- Is it bad that it lands you on source layers? It pulled remote data from the tile endpoint you provided and is showing you the source layers that were fetched.

- If there is layers in the JSON it appears that the auto-generation did work. I wonder why the layers view didn't refresh. We will have to look into this.

- Seems to be the same issue as above

- Red warning X has been fixed

I'll get on these issues right away. Thanks again!

**Comment by justenPalmer** [comment]
The layer refresh bug was found and squashed.

**Comment by pnorman** [comment]
> * Is it bad that it lands you on source layers? It pulled remote data from the tile endpoint you provided and is showing you the source layers that were fetched.

The layer refresh bug was making it so difficult to interact, let me go through the workflow and see if it's still a problem. Did I give you the tilejson I was using?

- I can't remove a style. If I go to style settings, actions, remove style it remains in the list

- When I create a style with auto-add layers I get the layers appearing, but the map itself didn't render until I went into the JSON and made a trivial edit.

- A compare functionality that lets me compare with an existing mapbox gl style or raster tileset would be helpful, akin to https://github.com/kosmtik/kosmtik-map-compare

- If the property name dropdown goes off screen, I can't scroll down to see all of it nor scroll down

![image](https://user-images.githubusercontent.com/1190866/80156953-03887400-857a-11ea-819b-551af27d9f9d.png)

**Comment by justenPalmer** [comment]
@pnorman I didn't try your tileJSON but the one I was using worked well.

- There was a bug in style removal but I did push up a fix. I think a refresh might fix the issue.

- That's strange the map didn't render right away for you. I'll try to replicate.

- Gretchen was also asking for a compare functionality. I'll have to think about a way to work that in.

- Yeah, those dropdowns should be scrollable once they appear. Which browser are you using?

**Comment by pnorman** [comment]
> * Yeah, those dropdowns should be scrollable once they appear. Which browser are you using?

Chrome on Windows 10, 81.0.4044.122 (Official Build) (64-bit) (cohort: Stable)

**Comment by pnorman** [comment]
Markdown in (i) text isn't being rendered
![image](https://user-images.githubusercontent.com/1190866/80264068-a4913080-8647-11ea-8d7d-a284d91eb884.png)

**Comment by justenPalmer** [comment]
@pnorman good catch! I'll def put a little markdown rendering in those tooltips.

**Comment by justenPalmer** [comment]
This version is now live! Closing this issue
