### ISSUE TITLE
Clone layer grayed out, not obvious how to use

### ISSUE THREAD

**Issue by pnorman** [go-spatial/fresco#88]
![image](https://user-images.githubusercontent.com/1190866/81520190-73c42300-92f8-11ea-91ac-9875627ae954.png)

The Clone Layer button does nothing, and it's not obvious how to enable it.

**Comment by justenPalmer** [comment]
Ah, good catch. I'll get that fixed.

**Comment by justenPalmer** [comment]
Clone layer functionality is now active!
