### ISSUE TITLE
Expected an even number of arguments mis-counts arrays

### ISSUE THREAD

**Issue by pnorman** [go-spatial/fresco#89]
![image](https://user-images.githubusercontent.com/1190866/81520812-28ab0f80-92fa-11ea-9ee0-f4a17f71059a.png)

The array for line-color has 6 arguments, which is even.

The error is it should have an odd number of arguments.

**Comment by justenPalmer** [comment]
Hmm, that error is actually being thrown by the Mapbox Gl renderer. I believe `match` expressions require a default case which would mean one more color after `trunk`, `#d1..`. I think it starts counting arguments after the expression is declared. So in this case, after match there are five arguments and it is expecting six.

**Comment by pnorman** [comment]
Ah, it seems like that's the case. Do we have control over the text? If we could say something like "Expected an even number of arguments to "match" expression" it would make it clearer.

**Comment by justenPalmer** [comment]
Right now I'm just reporting the copy that Mapbox GL generated but we could start putting in some custom messages based on specific fields if the copy is not clear,

**Comment by pnorman** [comment]
Probably not worth it if there's not many issues with the text. I'll close this and we can revisit if we find a lot of unclear text - or get upstream to change the text.
