### ISSUE TITLE
Drag and drop layer reordering

### ISSUE THREAD

**Issue by justenPalmer** [go-spatial/fresco#9]

**Comment by justenPalmer** [comment]
This is now in. Needs additional testing.

**Comment by ARolek** [comment]
First experience is pretty good. A few notes:

- There is no clear indicator the layer is drag and drop. I guess it could be considered "discoverable" once the user reaches the point where they want to drag and drop.
- Can you restrict the layer entries so they can only be dragged & drooped within the layer column?

Looking good.
