### ISSUE TITLE
String used for text-allow-overlap

### ISSUE THREAD

**Issue by pnorman** [go-spatial/fresco#90]
I added `text-allow-overlap` to a layer and set it to true. In the JSON this set it to `"true"`, a string instead of `true`, a boolean, and gave me an error.

![image](https://user-images.githubusercontent.com/1190866/81542140-0a103d00-9329-11ea-9b99-59d4f2327bb1.png)

**Comment by justenPalmer** [comment]
Definitely a bug, I'll get this fixed.

**Comment by justenPalmer** [comment]
This fix has been pushed to master
