### ISSUE TITLE
Mousing over a property (i) causes screen to flicker

### ISSUE THREAD

**Issue by pnorman** [go-spatial/fresco#94]
When I mouse over the (i) beside a property at the bottom of the screen the text that appears causes the (i) to move up and no longer under my mouse cursor. This causes it to disappear and move back to under my cursor.

![image](https://user-images.githubusercontent.com/1190866/83362943-39bfcd00-a34a-11ea-9f08-911b7224d2f9.png)
![image](https://user-images.githubusercontent.com/1190866/83362955-5956f580-a34a-11ea-9f55-d4989ff4a83b.png)

This is fairly sensitive to the exact position of the mouse.

**Comment by justenPalmer** [comment]
I just pushed up a fix for this. I built a tooltip that is aware of its position on the screen and will switch sides if it is too close to an edge.
